version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - .env:/var/www/html/.env
    command: >
      sh -c "
      php artisan key:generate &&
      php artisan serve --host=0.0.0.0 --port=8082"
    env_file:
      - .env
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: '%'
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge