name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Setup SSH key for remote server
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
    - name: Connect to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /opt
          git clone https://github.com/Vitaee/CrudLaravel.git
          cd CrudLaravel
          sudo docker-compose run --rm app composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Run tests
      uses: docker://php:8.1
      env:
        DB_CONNECTION: pgsql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      with:
        entrypoint: sh
        args: >
           -c "cd /opt/CrudLaravel
                && php artisan test"
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      if: success()
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd CrudLaravel
          sudo docker-compose up -d
